### ISSUE TITLE
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated

### ISSUE THREAD

**Issue by ilya2016** [RealGeeks/django-modelclone#21]
Hello,

I got a lot of these deprecation warning log messages - that complicates log analysis and the whole life, even with "django-admin --help".
Could you please update **ClonableModelAdmin.get_urls()** to avoid using **patterns()** when in Django 1.9, eg:
`new_urlpatterns = [ url(r'^(.+)/clone/$',
                self.admin_site.admin_view(self.clone_view),
                name=url_name), ]
`
Sorry for not providing pull request - I'm first time here and know nothing about test framework.

Thank you.
-Ilya

> 2016-03-16 20:58:20,917 __init__ - WARNING 10632 140559809300224 /opt/py3.5_venv/lib/python3.5/site-packages/modelclone/admin.py:47: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name=url_name)

.....
> (py3.5_venv) [root@qa-tools-dashboard py3.5_venv]# pip3.5 -vv list | grep -e Dja -e model
> Django (1.9.4)
> django-modelclone (0.5.3)

**Comment by davidkrisch** [comment]
Fixed in bb3a8350f1866638a946115a6a08040c007fbb9d
