### ISSUE TITLE
RemovedInDjango19Warning from use of get_formsets()

### ISSUE THREAD

**Issue by jklaiho** [RealGeeks/django-modelclone#22]
The following warning is being logged after upgrading a project from Django 1.7 to 1.8:

> /home/frank/virtualenvs/frank/src/django-modelclone/modelclone/admin.py:95: RemovedInDjango19Warning: ModelAdmin.get_formsets() is deprecated and will be removed in Django 1.9. Use ModelAdmin.get_formsets_with_inlines() instead.
>  `  for FormSet, inline in zip(self.get_formsets(request), inline_instances):`

**Comment by davidkrisch** [comment]
Fixed in df176ab9b00d1ca0dfedd623ff5100619e81bf25
