### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by djcoin** [RealGeeks/django-modelclone#26]
Hi there, thanks for the lib!

Well, so the pip is outdated, but I installed the version from master. I guess a page not found error when clicking on the button, here is the url : http://localhost:8000/admin/event/event/4/change/clone/ .
Error message: "event object with primary key u'4/change' does not exist."

Seems like an acute problem, does anyone have the same thing happening?

**Comment by bahendri** [comment]
Someone updated the get_url function without also updating the template. See https://github.com/RealGeeks/django-modelclone/commit/bb3a8350f1866638a946115a6a08040c007fbb9d.

They forgot to modify change_form.html to point to the new path. `href="clone/"` should be changed to `href="change/clone/"`

**Comment by davidkrisch** [comment]
New version (0.6.1) on PyPi with this fix:  https://pypi.python.org/pypi/django-modelclone/0.6.1
