### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by igorsobreira** [RealGeeks/django-modelclone#9]

**Comment by rouxxx** [comment]
ImportError: cannot import name 'force_unicode'

I guess this bug has its place here ;)

**Comment by igorsobreira** [comment]
Good catch @rouxxx.  If you're playing with python 3 let us know any issues you find.  Thanks!

**Comment by rouxxx** [comment]
A little update : 
- I replaced, in admin.py, "from django.utils.encoding import force_unicode" by "from django.utils.encoding import force_text" and the deployment works
- Using the duplicate button, I ran into this error "'dict' object has no attribute 'iterkeys'". In admin.py, line 103, I replaced "for name in vars(original_obj).iterkeys():" by "for name in vars(original_obj).keys():"

After modifying these two lines, the duplication works fine (for now).

I am not a big user of Github yet so I let you making the pull request needed ;)

**Comment by igorsobreira** [comment]
@rouxxx version 0.5.1 has these fixes. thanks!

**Comment by igorsobreira** [comment]
All our tests are passing with python 3.7
